[package]
name = "mountaindouw/textplus"
version = "1.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
faye = "mountaindouw/faye@1.9.2"
translatewrapper = "prophetouw/translatewrapper@1.0.6"