return {
    Default = require(script.Parent.Parent.Holder.Default);
    Rainbow = require(script.Parent.Parent.Holder.Rainbow);
    Fade = require(script.Parent.Parent.Holder.Fade),
    Wiggle = require(script.Parent.Parent.Holder.Wiggle);
    Pop = require(script.Parent.Parent.Holder.Pop);
    Shrink = require(script.Parent.Parent.Holder.Shrink);
    Rise = require(script.Parent.Parent.Holder.Rise);
    Drop = require(script.Parent.Parent.Holder.Drop);
}